name: compile_ubuntu

on: [push]

permissions:
  contents: read
  
env:
  WX_VERSION: "3.3.3"
  # BUILD_TYPE: Release

jobs:
  compile_latest_and_test:
    runs-on: ubuntu-22.04 #ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write

    steps:
      - name: Checkout_git
        uses: actions/checkout@v7
        with:
          fetch-depth: 15
      - name: install_packages
        run: |
             sudo apt-get update
             sudo apt-get install appstream appstream-util cmake desktop-file-utils doxygen gettext ninja-build pandoc xvfb at-spi2-core dbus po4a lintian weston tidy fuse libfuse2 libgtk-3-dev
      - name: validate_appdata
        run: |
             appstream-util validate data/4ChessViewer.appdata.xml
      - name: build_wxwidgets
        if: steps.cache_wx.outputs.cache-hit != 'true'
        run: |
             wget -q https://github.com/wxWidgets/wxWidgets/releases/download/v${{ env.WX_VERSION }}/wxWidgets-${{ env.WX_VERSION }}.tar.bz2
             tar xjf wxWidgets-${{ env.WX_VERSION }}.tar.bz2
             cd wxWidgets-${{ env.WX_VERSION }}
             mkdir Sbuild && cd Sbuild
             cmake -G "Ninja" -DCMAKE_INSTALL_PREFIX=/usr -DwxBUILD_SHARED=ON ..
             ninja
             DESTDIR=/opt/wxW-Temp ninja install
      - name: install_wxwidgets
        run: |
             sudo cp -a /opt/wxW-Temp/. /usr/
      - name: configure
        run: |
             export CXXFLAGS="-Wall -Wextra -ansi -Werror -Wpedantic"
             mkdir build
             cd build
             cmake -G "Ninja" ..
      - name: compile
        run: |
             cd build
             cmake --build .
      - name: download_linuxdeploy #appImage
        #if: startsWith(github.ref, 'refs/tags/v')
        run: |
          wget -q https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-x86_64.AppImage
      - name: appimage_Image
        #if: startsWith(github.ref, 'refs/tags/v')
        run: |
          mkdir -p AppDir/usr/bin
          cp build/4chessviewer AppDir/usr/bin/
          chmod +x AppDir/usr/bin/4chessviewer
          ./linuxdeploy-x86_64.AppImage \
            --appdir AppDir \
            --desktop-file data/4ChessViewer.desktop \
            --icon-file data/4ChessViewer.png \
            --output appimage
      - name: upload_artifact
        uses: actions/upload-artifact@v7
        with:
          name: 4ChessViewer-ubuntu-${{ github.sha }}
          path: ./4ChessViewer*.AppImage
          retention-days: 3
      - name: publish_release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v3
        with:
          files: |
            *.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
