name: compile_ubuntu

on: [push]

permissions:
  contents: read
  
env:
  WX_VERSION: "3.3.3"
  ID_FP: "io.github.bztd.FourChessViewer"
  VERSION_UBUNTU: "ubuntu-22.04"

jobs:
  compile_latest:
    runs-on: ubuntu-22.04 #ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write

    steps:
      - name: Checkout_git
        uses: actions/checkout@v7
        with:
          fetch-depth: 15
      - name: install_packages
        run: |
             sudo apt-get update
             sudo apt-get install appstream appstream-util cmake desktop-file-utils doxygen gettext ninja-build pandoc xvfb at-spi2-core dbus po4a lintian weston tidy libgtk-3-dev
      - name: validate_appdata
        run: |
             appstream-util validate data/4ChessViewer.appdata.xml
      - name: install_linuxdeploy #appImage
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
             wget -q https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
             chmod +x linuxdeploy-x86_64.AppImage
      - name: cache_wxwidgets
        id: cache_wx
        uses: actions/cache@v6
        with:
          path: /opt/wxW-Temp
          key: wxW-${{ env.WX_VERSION }}-${{ env.VERSION_UBUNTU }}
      - name: build_wxwidgets
        if: steps.cache_wx.outputs.cache-hit != 'true'
        run: |
             wget -q https://github.com/wxWidgets/wxWidgets/releases/download/v${{ env.WX_VERSION }}/wxWidgets-${{ env.WX_VERSION }}.tar.bz2
             tar xjf wxWidgets-${{ env.WX_VERSION }}.tar.bz2
             cd wxWidgets-${{ env.WX_VERSION }}
             mkdir Sbuild && cd Sbuild
             cmake -G "Ninja" -DCMAKE_INSTALL_PREFIX=/usr -DwxBUILD_SHARED=ON ..
             ninja
             DESTDIR=/opt/wxW-Temp ninja install
      - name: install_wxwidgets
        run: |
             sudo cp -a /opt/wxW-Temp/usr/. /usr/
             ls -la /usr/bin
      - name: configure
        run: |
             export CXXFLAGS="-Wall -Wextra -Werror -Wpedantic"
             mkdir build
             cd build
             cmake -G "Ninja" ..
      - name: compile
        run: |
             cd build
             cmake --build .
      - name: appimage_Image
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
             mkdir -p AppDir/usr/bin
             cp build/4chessviewer AppDir/usr/bin/
             chmod +x AppDir/usr/bin/4chessviewer
             ./linuxdeploy-x86_64.AppImage \
               --appdir AppDir \
               --desktop-file data/4ChessViewer.desktop \
               --icon-file data/4ChessViewer.png \
               --output appimage
      - name: publish_appImage
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v3
        with:
          files: |
            4ChessViewer*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  build_flatpak:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: compile_latest
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-25.08
      options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Build
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: 4ChessViewer.flatpak
          manifest-path: data/${{ env.ID_FP }}.yml
      - name: publish_flatpak
        uses: softprops/action-gh-release@v3
        with:
          files: |
            *.flatpak
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
